language: ruby
rvm:
- 2.6

sudo: false
dist: trusty

before_install:
 - gem install bundler
 - git clone --branch=publish https://github.com/adrianba/jekyll-adrianba.net.git ./_site

before_script:
 - chmod +x ./_deploy/cibuild.sh
 - chmod +x ./_deploy/deploy.sh

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./_deploy/cibuild.sh

after_success:
 - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./_deploy/deploy.sh; fi'

# branch whitelist
branches:
  only:
  - master

cache:
  bundler: true
  directories:
  - .cache

before_cache:
  mkdir -p .cache && cp .jekyll-metadata .cache

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - secure: "hMTqa6kLtxrbBDBgFCZ/W4vVcgB1WOL+oT8CmCYjRUv+08DVC5zXL8lh67HHXcmZXpazVEOcSP1JdoN9dZnADD8k/QJFzJ2zuyFodequ4Exh+0qiPsWsR+fDA23SHp3La2MCE+s1PCzvthGPNmUQG5xF2UrufsLlpEVY83LDyk3VmK8oP4Y6idTualdudcoHRwHhB5EUdrFrT1z8mU0NRe0w9guJQz5e/usvhzcADRPrl+Qir74+iT0UVG1oShPcwqaTayg7uoCjJu2p3IKWOXpdmzKBfp+E+MkaMqfi1in+mlZxioOHAwaXkFeT1J07ynW09lgFJz1Eb/Es1U33psE6RV9YhRU34wDk+Gmo1igPIft79j4QHku7DNqpROZU8Sd88zK/V3Te2vR+HbkVO0FI32RA3M5Q/O4Fxsnpu/MCy4iMJsOC1teOsVAoNqbDiVbwA4x5nn6bcAz8Pf6KJMVnMdIxmpukafjxuSz4Z38h64Cbn6u3Vbw6qsgMERDBlmCbV7oUXulcyLPmMBiQ/7+ugKmKvccQQXF8yLQetCx+FMyVWMUZ7RFl9sM7xr6yvEoyHtdlC/xosQ7cdsyhulp9ybH4IOMh3y8WN/5h6EwnPzsY0fka7bRca+UGVLibJpBIhy0rd5MNwPgcTvuD4pJmHhYJbJYr6Z+EggAMuHo="