name: Build and deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true

    steps:
      - name: Install dependencies
        run: sudo apt-get install libxslt-dev libxml2-dev

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Checkout publish
        uses: actions/checkout@v2
        with:
          path: _site
          ref: publish

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Cache Jekyll data
        uses: actions/cache@v2
        with:
          path: |
            .jekyll-cache
            .jekyll-metadata
          key: cache-20200803

      - name: Build
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Test
        run: bundle exec htmlproofer ./_site --disable-external --allow-hash-href --ignore-empty-alt --no-enforce-https

      - name: List
        run: ls -al && ls -al ./_site

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: chmod +x ./_deploy/deploy.sh && ./_deploy/deploy.sh
